# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conveyor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'conveyor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63onveyor.proto\x12\x08\x63onveyor\"\x9f\x01\n\nSensorData\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\r\n\x05speed\x18\x02 \x01(\x02\x12\x0f\n\x07voltage\x18\x03 \x01(\x02\x12\x0c\n\x04load\x18\x04 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x05 \x01(\x02\x12\r\n\x05power\x18\x06 \x01(\x02\x12\x0b\n\x03rpm\x18\x07 \x01(\x02\x12\x14\n\x0cmotor_torque\x18\x08 \x01(\x02\x12\x12\n\nefficiency\x18\t \x01(\x02\"w\n\x11OptimizedSettings\x12\x11\n\tnew_speed\x18\x01 \x01(\x02\x12\x13\n\x0bnew_voltage\x18\x02 \x01(\x02\x12\x12\n\nnew_pid_kp\x18\x03 \x01(\x02\x12\x12\n\nnew_pid_ki\x18\x04 \x01(\x02\x12\x12\n\nnew_pid_kd\x18\x05 \x01(\x02\x32\\\n\x0f\x43onveyorService\x12I\n\x14GetOptimizedSettings\x12\x14.conveyor.SensorData\x1a\x1b.conveyor.OptimizedSettingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conveyor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=29
  _globals['_SENSORDATA']._serialized_end=188
  _globals['_OPTIMIZEDSETTINGS']._serialized_start=190
  _globals['_OPTIMIZEDSETTINGS']._serialized_end=309
  _globals['_CONVEYORSERVICE']._serialized_start=311
  _globals['_CONVEYORSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
