# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conveyor_pb2 as conveyor__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conveyor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConveyorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOptimizedSettings = channel.unary_unary(
                '/conveyor.ConveyorService/GetOptimizedSettings',
                request_serializer=conveyor__pb2.SensorData.SerializeToString,
                response_deserializer=conveyor__pb2.OptimizedSettings.FromString,
                _registered_method=True)


class ConveyorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOptimizedSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConveyorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOptimizedSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptimizedSettings,
                    request_deserializer=conveyor__pb2.SensorData.FromString,
                    response_serializer=conveyor__pb2.OptimizedSettings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conveyor.ConveyorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conveyor.ConveyorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConveyorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOptimizedSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conveyor.ConveyorService/GetOptimizedSettings',
            conveyor__pb2.SensorData.SerializeToString,
            conveyor__pb2.OptimizedSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
