apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 3000
            - containerPort: 8080
          env:
            - name: OLLAMA_API_BASE
              value: "http://ollama:11434"
            - name: DEBUG
              value: "true"
          volumeMounts:
            - mountPath: "/app/data"
              name: webui-storage
      volumes:
        - name: webui-storage
          persistentVolumeClaim:
            claimName: webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 8080
      targetPort: 8080
