services:
  ollama:
    build: ./ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s  # Give 5 minutes for initial setup and model download

  crewai_app:
    build: ./src/icsagents/
    container_name: crewai_app
    depends_on: 
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    command: ["python", "main.py"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:3000"  # Expose Open WebUI on port 3000
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - DEBUG=true  # Optional: Enable debugging logs
    depends_on:
      ollama:
        condition: service_healthy  # Ensure Ollama is healthy before WebUI starts
    volumes:
      - webui_data:/app/data

volumes:
  ollama_data:
  webui_data: